CREATE TABLE `demo_user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`userName` VARCHAR(32) NOT NULL,
	`passWord` VARCHAR(32) NOT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=22;
