package net.begincode.core.mapper;

import java.util.List;
import net.begincode.core.model.AnsAgree;
import net.begincode.core.model.AnsAgreeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;


public interface AnsAgreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int countByExample(AnsAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int deleteByExample(AnsAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ansAgreeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int insert(AnsAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int insertSelective(AnsAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    List<AnsAgree> selectByExampleWithRowbounds(AnsAgreeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    List<AnsAgree> selectByExample(AnsAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    AnsAgree selectByPrimaryKey(Integer ansAgreeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AnsAgree record, @Param("example") AnsAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AnsAgree record, @Param("example") AnsAgreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AnsAgree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ans_agree
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AnsAgree record);
}