package net.begincode.core.mapper;

import java.util.List;
import net.begincode.core.model.ProAttention;
import net.begincode.core.model.ProAttentionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProAttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int countByExample(ProAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int deleteByExample(ProAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer proAttentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int insert(ProAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int insertSelective(ProAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    List<ProAttention> selectByExampleWithRowbounds(ProAttentionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    List<ProAttention> selectByExample(ProAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    ProAttention selectByPrimaryKey(Integer proAttentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProAttention record, @Param("example") ProAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProAttention record, @Param("example") ProAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_attention
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProAttention record);
}