package net.begincode.core.model;

import java.io.Serializable;
import java.util.Date;

public class Problem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_id
     *
     * @mbggenerated
     */
    private Integer problemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.vote_count
     *
     * @mbggenerated
     */
    private Integer voteCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.collect_count
     *
     * @mbggenerated
     */
    private Integer collectCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.view_count
     *
     * @mbggenerated
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.solve
     *
     * @mbggenerated
     */
    private Integer solve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.delete_flag
     *
     * @mbggenerated
     */
    private Integer deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.feedback
     *
     * @mbggenerated
     */
    private Integer feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.begincode_user_id
     *
     * @mbggenerated
     */
    private Integer begincodeUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.answer_count
     *
     * @mbggenerated
     */
    private Integer answerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table problem
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_id
     *
     * @return the value of problem.problem_id
     *
     * @mbggenerated
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_id
     *
     * @param problemId the value for problem.problem_id
     *
     * @mbggenerated
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.title
     *
     * @return the value of problem.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.title
     *
     * @param title the value for problem.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.user_name
     *
     * @return the value of problem.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.user_name
     *
     * @param userName the value for problem.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.create_time
     *
     * @return the value of problem.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.create_time
     *
     * @param createTime the value for problem.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.update_time
     *
     * @return the value of problem.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.update_time
     *
     * @param updateTime the value for problem.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.vote_count
     *
     * @return the value of problem.vote_count
     *
     * @mbggenerated
     */
    public Integer getVoteCount() {
        return voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.vote_count
     *
     * @param voteCount the value for problem.vote_count
     *
     * @mbggenerated
     */
    public void setVoteCount(Integer voteCount) {
        this.voteCount = voteCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.collect_count
     *
     * @return the value of problem.collect_count
     *
     * @mbggenerated
     */
    public Integer getCollectCount() {
        return collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.collect_count
     *
     * @param collectCount the value for problem.collect_count
     *
     * @mbggenerated
     */
    public void setCollectCount(Integer collectCount) {
        this.collectCount = collectCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.view_count
     *
     * @return the value of problem.view_count
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.view_count
     *
     * @param viewCount the value for problem.view_count
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.solve
     *
     * @return the value of problem.solve
     *
     * @mbggenerated
     */
    public Integer getSolve() {
        return solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.solve
     *
     * @param solve the value for problem.solve
     *
     * @mbggenerated
     */
    public void setSolve(Integer solve) {
        this.solve = solve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.delete_flag
     *
     * @return the value of problem.delete_flag
     *
     * @mbggenerated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.delete_flag
     *
     * @param deleteFlag the value for problem.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.feedback
     *
     * @return the value of problem.feedback
     *
     * @mbggenerated
     */
    public Integer getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.feedback
     *
     * @param feedback the value for problem.feedback
     *
     * @mbggenerated
     */
    public void setFeedback(Integer feedback) {
        this.feedback = feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.begincode_user_id
     *
     * @return the value of problem.begincode_user_id
     *
     * @mbggenerated
     */
    public Integer getBegincodeUserId() {
        return begincodeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.begincode_user_id
     *
     * @param begincodeUserId the value for problem.begincode_user_id
     *
     * @mbggenerated
     */
    public void setBegincodeUserId(Integer begincodeUserId) {
        this.begincodeUserId = begincodeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.answer_count
     *
     * @return the value of problem.answer_count
     *
     * @mbggenerated
     */
    public Integer getAnswerCount() {
        return answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.answer_count
     *
     * @param answerCount the value for problem.answer_count
     *
     * @mbggenerated
     */
    public void setAnswerCount(Integer answerCount) {
        this.answerCount = answerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.content
     *
     * @return the value of problem.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.content
     *
     * @param content the value for problem.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
}